M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Sun May 28 09:25:34 2023
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-05-28T09:25:34+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X137706Y-104824
X137706Y-109824
X137706Y-114824
T0
M30
